FROM nginx:alpine

# Remove the default virtual host
RUN rm /etc/nginx/conf.d/default.conf

# Copy your Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy website files
COPY . /usr/share/nginx/html

RUN rm /usr/share/nginx/html/dockerfile

RUN rm /usr/share/nginx/html/nginx.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]